[package]
versioned_files = ["Cargo.toml", "Cargo.lock"]
changelog = "CHANGELOG.md"

[github]
owner = "NixOS"
repo = "nixpkgs-vet"

[release_notes]
change_templates = [
    "### $summary ($commit_hash)\n\n$details\n\nBy $commit_author_name",
    "* **$summary** by $commit_author_name ($commit_hash)",
    "### $summary\n\n$details",
    "* **$summary**",
]
extra_changelog_sections = [
    { types = ["major"], name = "Major changes" },
    { types = ["minor"], name = "Minor changes" },
    { types = ["patch"], name = "Patch changes" },
    { types = ["note"], footers = ["Changelog-Note"], name = "Notes" }
]


# prepare-release workflow
[[workflows]]
name = "prepare-release"

[[workflows.steps]]
type = "Command"
command = "git switch -c release"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows.steps]]
type = "Command"
command = "git commit -m \"chore: prepare release $version\""

[[workflows.steps]]
type = "Command"
command = "git push --force --set-upstream origin release"

[[workflows.steps]]
type = "CreatePullRequest"
base = "main"

[workflows.steps.title]
template = "chore: prepare release $version"

[workflows.steps.body]
template = "This PR was created by Knope. Merging it will create a new release.\n\n$changelog"

# release workflow
[[workflows]]
name = "release"

[[workflows.steps]]
type = "Release"

# document-change workflow
[[workflows]]
name = "document-change"
help_text = "Create a new change file to be included in the next release"

[[workflows.steps]]
type = "CreateChangeFile"

# get-version workflow
[[workflows]]
name = "get-version"
help_text = "Get the current version of the project"

[[workflows.steps]]
type = "Command"
command = 'echo "$version"'
