name: CI
on:
  pull_request:
  push:
    branches:
      - main

# This makes sure to only run one instance of this workflow per individual PR and pushes.
# We need this especially for the release step, because it has side effects.
# But it's also good in general, there's no need to finish action runs for commits
# when you push another one right after.
# Assumption: We push less frequently than it takes for this workflow to finish
concurrency:
  # For a push to the main branch, github.ref is refs/heads/<branch_name>
  # For a pull request, github.ref is refs/pull/<pr_number>/merge
  group: ${{ github.ref }}
  # We don't want to cancel in progress workflows for pushes to the main branch,
  # because it could be in the process of doing a release.
  # Better wait until it's done
  cancel-in-progress: ${{ github.event_name != 'pull' }}

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
        with:
          extra_nix_config: |
            max-jobs = 1

      # This can't be done in the treefmt check because it needs network access
      - name: check action pins
        run: nix run -f default.nix pkgs.pinact -- run -check -verify -diff

      - name: build
        run: nix-build -A ci

  prepare-release:
    # Skip merges from releases
    if: >-
      github.event_name == 'push' &&
      !contains(github.event.head_commit.message, 'chore: prepare release')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        if: vars.NIXPKGS_VET_CI_CLIENT_ID
        id: app-token
        with:
          client-id: ${{ vars.NIXPKGS_VET_CI_CLIENT_ID }}
          private-key: ${{ secrets.NIXPKGS_VET_CI_APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: true
          token: ${{ steps.app-token.outputs.token || github.token }}

      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6

      - name: Get GitHub App User ID
        id: get-user-id
        if: vars.NIXPKGS_VET_CI_CLIENT_ID
        run: echo "user-id=$(gh api "/users/$TOKEN_USERNAME" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          TOKEN_USERNAME: ${{ steps.app-token.outputs.app-slug }}[bot]
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Configure git
        run: |
          git config --global user.name "$TOKEN_USERNAME"
          git config --global user.email "$TOKEN_USER_ID+$TOKEN_USERNAME@users.noreply.github.com"
        env:
          TOKEN_USERNAME: ${{ steps.app-token.outputs.app-slug || 'github-actions' }}[bot]
          TOKEN_USER_ID: ${{ steps.get-user-id.outputs.user-id || '41898282' }}

      - name: store pre-bump version
        id: pre-bump
        run: echo "version=$(nix run -f default.nix pkgs.knope -- get-version)" >> "$GITHUB_OUTPUT"

      - name: prepare release
        run: nix run -f default.nix pkgs.knope -- prepare-release --verbose
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token || github.token }}

      - name: store post-bump version
        id: post-bump
        run: echo "version=$(nix run -f default.nix pkgs.knope -- get-version)" >> "$GITHUB_OUTPUT"

      - name: create release PR
        if: "${{ steps.pre-bump.outputs.version != steps.post-bump.outputs.version }}"
        run: nix run -f default.nix pkgs.knope -- push-draft-release --verbose
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token || github.token }}

  release:
    # Only run when a release PR is merged
    if: >-
      github.event_name == 'push' &&
      contains(github.event.head_commit.message, 'chore: prepare release')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        if: vars.NIXPKGS_VET_CI_CLIENT_ID
        id: app-token
        with:
          client-id: ${{ vars.NIXPKGS_VET_CI_CLIENT_ID }}
          private-key: ${{ secrets.NIXPKGS_VET_CI_APP_PRIVATE_KEY }}
          permission-contents: write

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: true
          token: ${{ steps.app-token.outputs.token || github.token }}

      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6

      - name: run knope
        run: nix run -f default.nix pkgs.knope -- release --verbose
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token || github.token }}

  # Make sure that all links in Markdown documents are valid
  xrefcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      # While this has a Nix build available, it needs to evaluate and build so much
      # that I don't think it's worth adding it to the nix-build.
      - uses: serokell/xrefcheck-action@81d3967156933307f52fc52f8dc7fa5e947509c2 # v1.0.3
        with: # Invalid symlinks for testing purposes.
          xrefcheck-args: >
            --ignore tests/symlink-invalid/main/pkgs/by-name/fo/foo/foo
            --ignore tests/multiple-failures/main/pkgs/by-name/A/fo@/foo
