name: CI
on:
  pull_request:
  push:
    branches:
      - main

# This makes sure to only run one instance of this workflow per individual PR and pushes.
# We need this especially for the release step, because it has side effects.
# But it's also good in general, there's no need to finish action runs for commits
# when you push another one right after.
# Assumption: We push less frequently than it takes for this workflow to finish
concurrency:
  # For a push to the main branch, github.ref is refs/heads/<branch_name>
  # For a pull request, github.ref is refs/pull/<pr_number>/merge
  group: ${{ github.ref }}
  # We don't want to cancel in progress workflows for pushes to the main branch,
  # because it could be in the process of doing a release.
  # Better wait until it's done
  cancel-in-progress: ${{ github.event_name != 'pull' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b # v31.10.4
        with:
          extra_nix_config: |
            max-jobs = 1

      - name: build
        run: nix-build -A ci

      - name: release
        if: ${{ github.event_name == 'push' }}
        run: scripts/release.sh
        env:
          GH_TOKEN: ${{ github.token }}

  # Make sure that all links in Markdown documents are valid
  xrefcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # While this has a Nix build available, it needs to evaluate and build so much
      # that I don't think it's worth adding it to the nix-build.
      - uses: serokell/xrefcheck-action@81d3967156933307f52fc52f8dc7fa5e947509c2 # v1.0.3
        with: # Invalid symlinks for testing purposes.
          xrefcheck-args: >
            --ignore tests/symlink-invalid/main/pkgs/by-name/fo/foo/foo
            --ignore tests/multiple-failures/main/pkgs/by-name/A/fo@/foo
